server.tomcat.threads.max=${SERVER_TOMCAT_THREADS_MAX:200}
server.tomcat.threads.min-spare=${SERVER_TOMCAT_THREADS_MIN_SPARE:10}

# Database
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.url=${DB_URL:}

# Redis Cache
redis.pool.db=${REDIS_DB:1}
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}
redis.password=${REDIS_PASSWORD:}

spring.devtools.restart.enabled=false
