# System Service
server.servlet.session.cookie.secure=true

# Database
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.url=${DB_URL:}

# Redis Cache
redis.pool.db=${REDIS_DB:5}
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}
redis.password=${REDIS_PASSWORD:}

# Sentry
sentry.dsn=${SENTRY_DSN:}
sentry.send-default-pii=${SENTRY_SEND_DEFAULT_PII:false}
sentry.traces-sample-rate=${SENTRY_TRACES_SAMPLE_RATE:0.0}
